// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwEhZIfATyFm1sztHX7SLhzaiC7qRDSPI',
    appId: '1:723604083154:web:cbf8ac37947739592b380b',
    messagingSenderId: '723604083154',
    projectId: 'smarket-2fc3c',
    authDomain: 'smarket-2fc3c.firebaseapp.com',
    storageBucket: 'smarket-2fc3c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7wvGpe-nRtk4KDfae08zuxtYlAEV77o4',
    appId: '1:723604083154:android:d391b94d97703aff2b380b',
    messagingSenderId: '723604083154',
    projectId: 'smarket-2fc3c',
    storageBucket: 'smarket-2fc3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVdDs60Lb1CKojvO_hHRMdjRNH21Nwzxs',
    appId: '1:723604083154:ios:9bda9d3a9900a5e72b380b',
    messagingSenderId: '723604083154',
    projectId: 'smarket-2fc3c',
    storageBucket: 'smarket-2fc3c.firebasestorage.app',
    iosClientId: '723604083154-npm2t2ii01u26t07u8hutea8da8vs0gi.apps.googleusercontent.com',
    iosBundleId: 'com.example.smarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVdDs60Lb1CKojvO_hHRMdjRNH21Nwzxs',
    appId: '1:723604083154:ios:9bda9d3a9900a5e72b380b',
    messagingSenderId: '723604083154',
    projectId: 'smarket-2fc3c',
    storageBucket: 'smarket-2fc3c.firebasestorage.app',
    iosClientId: '723604083154-npm2t2ii01u26t07u8hutea8da8vs0gi.apps.googleusercontent.com',
    iosBundleId: 'com.example.smarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwEhZIfATyFm1sztHX7SLhzaiC7qRDSPI',
    appId: '1:723604083154:web:756db5f9720d65442b380b',
    messagingSenderId: '723604083154',
    projectId: 'smarket-2fc3c',
    authDomain: 'smarket-2fc3c.firebaseapp.com',
    storageBucket: 'smarket-2fc3c.firebasestorage.app',
  );
}
